name: 'Update Azure API Management OpenAPI schema'
description: 'This GitHub Action allows you to update your Azure API Management OpenAPI schema using a file or a relative URL'
author: 'Ossi Pesonen'
inputs:
  openAPIDefinitions:
    required: true
    description: 'Relative URL or path to a OpenAPI JSON schema file'
  apiManagementApiUrl:
    required: true
    description: 'API Management API endpoint URL with your subscription ID, resource group, service name etc.'
  credentials:
    required: true
    description: 'API Management credentials'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: black
